// Renders trusted first-party hub pages served with NO CSP sandbox — today
// only `/oura/` (`docs/inventory/assets.md` §9): generated by our own cron
// scripts, carries inline JS (theme toggle, tooltips) and reads/writes
// `localStorage['hub-theme']`, the same key the hub shell itself uses.
// Deliberately a SEPARATE component from BriefWebView (docs/research/briefs.md
// §8) so the brief's locked-down defaults can never be accidentally relaxed
// by a shared config surface: JS on, persistent (non-incognito) data store so
// the theme preference sticks across opens, same-origin navigation lock.
import { useCallback, useRef, useState } from 'react';
import { StyleSheet, View, type StyleProp, type ViewStyle } from 'react-native';
import * as WebBrowser from 'expo-web-browser';
import WebView from 'react-native-webview';
import { useTheme } from '../../theme/useTheme';
import { StatePanel } from '../shell';
import { decideTrustedNavigation } from './webViewPolicy';

export interface TrustedPageViewProps {
  /** Absolute https(s) URL on the hub host, e.g. `${HUB_ORIGIN}/oura/`. */
  uri: string;
  style?: StyleProp<ViewStyle>;
  testID?: string;
}

export function TrustedPageView({ uri, style, testID }: TrustedPageViewProps) {
  const { t } = useTheme();
  const ref = useRef<WebView>(null);
  const [error, setError] = useState<string | null>(null);

  const onShouldStartLoadWithRequest = useCallback((req: { url: string }) => {
    const decision = decideTrustedNavigation(req.url);
    if (decision === 'external') {
      WebBrowser.openBrowserAsync(req.url);
      return false;
    }
    return decision === 'allow';
  }, []);

  if (error) {
    return <StatePanel tone="error" title="Page unavailable" detail={error} />;
  }

  return (
    <View style={[styles.container, { backgroundColor: t('bg-0') }, style]} testID={testID}>
      <WebView
        ref={ref}
        source={{ uri }}
        javaScriptEnabled
        incognito={false}
        startInLoadingState
        renderLoading={() => <StatePanel tone="pending" title="Loading…" />}
        onShouldStartLoadWithRequest={onShouldStartLoadWithRequest}
        onContentProcessDidTerminate={() => ref.current?.reload()}
        onError={(e) => setError(e.nativeEvent.description)}
        onHttpError={(e) => setError(`${e.nativeEvent.url} → ${e.nativeEvent.statusCode}`)}
        style={styles.webview}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  webview: { flex: 1, backgroundColor: 'transparent' },
});
